### ISSUE TITLE
Randomly stops after around 8k or so

### ISSUE THREAD

**Issue by AceBeaker2** [verlox/SendIt-Spammer#10]
https://user-images.githubusercontent.com/78876983/224785242-77d46b0f-a9db-4abb-a9b3-c7980a94ce97.mp4

just stops :P

**Comment by AceBeaker2** [comment]
nvm it seems to be caused by setting the connection limit too high burh

**Comment by AceBeaker2** [comment]
nvm still happens

**Comment by verlox** [comment]
to be completely honest, im not really sure whats causing that for you, i have hit 28k sent requests and cannot seem to replicate the behavior in the video.

**Comment by AceBeaker2** [comment]
One thing to note is that if i have multiple instances running, they all kinda speed themselves up and slow themselves down so that they stop at roughly the same amount of requests. Its very strange

**Comment by verlox** [comment]
yeah tbh, i think thats something to do with either your computer or provider, i havent encountered that issue at all throughout testing, but i also do not run multiple instances or recommend it.
