### ISSUE TITLE
Improvement/suggestion

### ISSUE THREAD

**Issue by ExamV1** [verlox/SendIt-Spammer#11]
Just a heads up that you can bypass the character limit on sendit by editing 'maxlength="170"' in the html to like 99999 and will still send, and it can crash the users sendit app when they try open the message.

![image](https://user-images.githubusercontent.com/87576045/224802817-4905be7d-0663-4889-94a6-4d0f3f55ebd9.png)

![image](https://user-images.githubusercontent.com/87576045/224803294-563b5e33-efba-42cc-bdf6-43444f45856a.png)

Here you can see it sent:
![image](https://user-images.githubusercontent.com/87576045/224803789-cddd4e45-938f-4621-8bfa-b33c88501271.png)
![image](https://user-images.githubusercontent.com/87576045/224803813-7b576523-4141-4fe4-ae9d-d1deec63a088.png)

**Comment by verlox** [comment]
nice find, but since it works off of raw requests, and doesnt render the webpage at all, it doesnt need to edit any html.
