### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by SCI-O** [verlox/SendIt-Spammer#2]
![image](https://user-images.githubusercontent.com/86878812/171972062-4858bec1-5a95-412a-9c1d-250a49dfe62e.png)

**Comment by verlox** [comment]
fixed in 483453c0ed69f226e84721bdd58f28fea08318d8. [Download](https://github.com/verlox/SendIt-Spammer/releases/tag/v1.3)
