### ISSUE TITLE
3 sendits then stops

### ISSUE THREAD

**Issue by Opticz0005** [verlox/SendIt-Spammer#3]
I ran the spammer as admin (just in case) and it sent 3 sendits and that's all I got on my phone. The command prompt said i sent over 3500 requests. if my math is right, 3 does not equal 3500.

**Comment by verlox** [comment]
they mustve updated again, and ill work on adding proxy support, but the api still says its being created, and its not showing, so they did some dumbass internal shit

**Comment by verlox** [comment]
[Download](https://github.com/verlox/SendIt-Spammer/releases/tag/v1.4) the fix
Fix commit: feefcef9d366e4a3523d8b93a0b57669caa55c0b

**Comment by NicholasDominici** [comment]
And I'll do that dumbass shit again, don't test me.

**Comment by russianheavy1337** [comment]
HAHAHHAHAHHAHAHAHAHHAHHAAH LOL

**Comment by verlox** [comment]
cope harder + ur api was downed by a shitty spammer, consider running sendit off of something better than a 15 year old laptop you found in a trash bin

**Comment by verlox** [comment]
> And I'll do that dumbass shit again, don't test me.

![image](https://user-images.githubusercontent.com/83199049/179259341-0a1d6da6-798f-497c-b368-88319720e6a4.png)
ill test my luck
