### ISSUE TITLE
getting errors whilst starting

### ISSUE THREAD

**Issue by heckeroncrack** [verlox/SendIt-Spammer#7]
![photo](https://user-images.githubusercontent.com/124959846/222986111-695208e9-0dc5-4c64-b1c7-73615dec8046.png)

**Comment by verlox** [comment]
ill look into it rq

**Comment by verlox** [comment]
they updated their api, updated version that works [here](https://github.com/verlox/SendIt-Spammer/releases/tag/v1.8)
